# Site settings
title: A Blog of Computer Science
email: bryanktidwell2@gmail.com
description: ># this means to ignore newlines until "baseurl:"
  I'm a software engineer with opinions
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://DwordPtr.github.io" # the base hostname & protocol for your site
github_username:  DwordPtr
linkedin_username: bryantidwell2

# Build settings
markdown: kramdown
